/**
 * Tech glossary — single source of truth for Formula 1 technical terms.
 *
 * Used by /tech-glossary (the reference page) and by <GlossaryLink> (internal
 * linking: matches these terms inside story/body text and links them here).
 *
 * `slug` is the anchor on /tech-glossary (#slug). `aliases` are extra surface
 * forms the linker should also catch (e.g. "DRS" plus "Drag Reduction System").
 * Keep terms ordered alphabetically by `term`.
 */

export type GlossaryCategory =
  | 'Aerodynamics'
  | 'Power Unit'
  | 'Tyres'
  | 'Chassis'
  | 'Strategy'
  | 'Regulations';

export type TermDiagramId =
  | 'diffuser'
  | 'downforce'
  | 'drs'
  | 'ers'
  | 'ground-effect'
  | 'slipstream'
  | 'turbo'
  | 'active-suspension'
  | 'graining'
  | 'parc-ferme'
  | 'undercut';

export interface GlossaryTerm {
  slug: string;
  term: string;
  category: GlossaryCategory;
  aliases?: string[];
  definition: string;
  /** Micro badge, e.g. "AERO // REGULATION 2022". */
  badge: string;
  /** Optional one-line engineering note. */
  keyImpact?: string;
  diagram?: TermDiagramId;
}

export const glossaryTerms: GlossaryTerm[] = [
  {
    slug: 'active-suspension',
    term: 'Active Suspension',
    category: 'Chassis',
    badge: 'CHASSIS // BANNED 1994',
    diagram: 'active-suspension',
    keyImpact: 'Williams FW14B/FW15C kept the platform at aero optimum lap after lap.',
    definition:
      'A computer-controlled suspension that adjusts ride height and stiffness in real time to keep the car at its aerodynamic optimum. Dominant in the early 1990s before being banned for 1994.',
  },
  {
    slug: 'diffuser',
    term: 'Diffuser',
    category: 'Aerodynamics',
    aliases: ['double diffuser'],
    badge: 'AERO // FLOOR',
    diagram: 'diffuser',
    keyImpact: 'Expands underbody flow at the exit — primary rear-downforce generator.',
    definition:
      'The upswept rear section of the floor that accelerates airflow under the car and expands it at the exit, lowering pressure to generate downforce. The 2009 double diffuser exploited a regulatory loophole to enormous effect.',
  },
  {
    slug: 'downforce',
    term: 'Downforce',
    category: 'Aerodynamics',
    badge: 'AERO // LOAD',
    diagram: 'downforce',
    keyImpact: 'More load = higher cornering speed, paid for in straight-line drag.',
    definition:
      'Aerodynamic load pressing the car onto the track, increasing mechanical grip through the tyres. More downforce means higher cornering speed at the cost of straight-line drag.',
  },
  {
    slug: 'drs',
    term: 'DRS',
    category: 'Aerodynamics',
    aliases: ['Drag Reduction System'],
    badge: 'AERO // REGULATION',
    diagram: 'drs',
    keyImpact: '~10–12 km/h top-speed delta on activation in a DRS zone.',
    definition:
      'Drag Reduction System: a driver-operated flap in the rear wing that opens within designated zones to cut drag and aid overtaking, permitted only when within one second of the car ahead.',
  },
  {
    slug: 'ers',
    term: 'ERS',
    category: 'Power Unit',
    aliases: ['Energy Recovery System', 'KERS'],
    badge: 'PU // HYBRID',
    diagram: 'ers',
    keyImpact: 'MGU-K deploy ≈ 160 hp; MGU-H harvests exhaust heat into the same battery.',
    definition:
      'Energy Recovery System: harvests energy under braking (MGU-K) and from exhaust heat (MGU-H), stores it in a battery, and redeploys it for extra power. Its forerunner, KERS, appeared in 2009.',
  },
  {
    slug: 'graining',
    term: 'Graining',
    category: 'Tyres',
    badge: 'TYRES // SURFACE',
    diagram: 'graining',
    keyImpact: 'Cold or sliding rubber rolls into strips — contact patch and grip collapse.',
    definition:
      'A surface tearing of the tyre where rubber rolls into small strips, reducing the contact patch and grip. Caused by sliding on a cold or overworked tyre.',
  },
  {
    slug: 'ground-effect',
    term: 'Ground Effect',
    category: 'Aerodynamics',
    badge: 'AERO // REGULATION 2022',
    diagram: 'ground-effect',
    keyImpact: '2022 regs moved a large share of downforce back into the floor / venturi tunnels.',
    definition:
      'Downforce generated by shaping the floor and underbody to create a low-pressure region beneath the car. Central to late-1970s/early-1980s design and reintroduced under the 2022 regulations.',
  },
  {
    slug: 'parc-ferme',
    term: 'Parc Fermé',
    category: 'Regulations',
    badge: 'REGS // SPORTING',
    diagram: 'parc-ferme',
    keyImpact: 'Qualifying setup is locked for the race, save a short list of legal tweaks.',
    definition:
      'The state, beginning at qualifying, in which teams may not change a car\'s setup. It locks the car into its qualifying configuration for the race save for a narrow list of permitted adjustments.',
  },
  {
    slug: 'slipstream',
    term: 'Slipstream',
    category: 'Aerodynamics',
    aliases: ['tow'],
    badge: 'AERO // WAKE',
    diagram: 'slipstream',
    keyImpact: 'The tow cuts drag for the following car — classic overtake set-up on long straights.',
    definition:
      'The pocket of low-pressure air behind a car. A following driver in the tow experiences less drag and can carry more speed to set up an overtake.',
  },
  {
    slug: 'turbo',
    term: 'Turbo',
    category: 'Power Unit',
    aliases: ['turbocharger', 'turbocharged'],
    badge: 'PU // HYBRID',
    diagram: 'turbo',
    keyImpact: '2014+ hybrid PU: single turbo paired with the MGU-H on the same shaft.',
    definition:
      'A compressor driven by exhaust gases that forces more air into the engine for greater power. Defined the original turbo era (1977–1988) and returned with the hybrid power units in 2014.',
  },
  {
    slug: 'undercut',
    term: 'Undercut',
    category: 'Strategy',
    badge: 'STRATEGY // PIT WALL',
    diagram: 'undercut',
    keyImpact: 'Typical undercut window: ~1.5–2.5s of fresh-tyre delta versus the car left out.',
    definition:
      'A strategy where a driver pits earlier than a rival and uses fresh-tyre pace to leapfrog them once the rival stops. The opposite move — staying out for track position — is the overcut.',
  },
];

/** Map for O(1) lookup by slug. */
export const glossaryBySlug: Record<string, GlossaryTerm> = Object.fromEntries(
  glossaryTerms.map((t) => [t.slug, t]),
);
