/**
 * Tech glossary — single source of truth for Formula 1 technical terms.
 *
 * Used by /tech-glossary (the reference page) and by <GlossaryLink> (internal
 * linking: matches these terms inside story/body text and links them here).
 *
 * `slug` is the anchor on /tech-glossary (#slug). `aliases` are extra surface
 * forms the linker should also catch (e.g. "DRS" plus "Drag Reduction System").
 * Keep terms ordered alphabetically by `term`.
 */

export interface GlossaryTerm {
  slug: string;
  term: string;
  category: 'Aerodynamics' | 'Power Unit' | 'Tyres' | 'Chassis' | 'Strategy' | 'Regulations';
  aliases?: string[];
  definition: string;
}

export const glossaryTerms: GlossaryTerm[] = [
  {
    slug: 'active-suspension',
    term: 'Active Suspension',
    category: 'Chassis',
    definition:
      'A computer-controlled suspension that adjusts ride height and stiffness in real time to keep the car at its aerodynamic optimum. Dominant in the early 1990s (notably the Williams FW14B/FW15C) before being banned for 1994.',
  },
  {
    slug: 'diffuser',
    term: 'Diffuser',
    category: 'Aerodynamics',
    aliases: ['double diffuser'],
    definition:
      'The upswept rear section of the floor that accelerates airflow under the car and expands it at the exit, lowering pressure to generate downforce. The 2009 "double diffuser" exploited a regulatory loophole to enormous effect.',
  },
  {
    slug: 'downforce',
    term: 'Downforce',
    category: 'Aerodynamics',
    definition:
      'Aerodynamic load pressing the car onto the track, increasing mechanical grip through the tyres. More downforce means higher cornering speed at the cost of straight-line drag.',
  },
  {
    slug: 'drs',
    term: 'DRS',
    category: 'Aerodynamics',
    aliases: ['Drag Reduction System'],
    definition:
      'Drag Reduction System: a driver-operated flap in the rear wing that opens within designated zones to cut drag and aid overtaking, permitted only when within one second of the car ahead.',
  },
  {
    slug: 'ers',
    term: 'ERS',
    category: 'Power Unit',
    aliases: ['Energy Recovery System', 'KERS'],
    definition:
      'Energy Recovery System: harvests energy under braking (MGU-K) and from exhaust heat (MGU-H), stores it in a battery, and redeploys it for extra power. Its forerunner, KERS, appeared in 2009.',
  },
  {
    slug: 'graining',
    term: 'Graining',
    category: 'Tyres',
    definition:
      'A surface tearing of the tyre where rubber rolls into small strips, reducing the contact patch and grip. Caused by sliding on a cold or overworked tyre.',
  },
  {
    slug: 'ground-effect',
    term: 'Ground Effect',
    category: 'Aerodynamics',
    definition:
      'Downforce generated by shaping the floor and underbody to create a low-pressure region beneath the car. Central to late-1970s/early-1980s design and reintroduced under the 2022 regulations.',
  },
  {
    slug: 'parc-ferme',
    term: 'Parc Fermé',
    category: 'Regulations',
    definition:
      'The state, beginning at qualifying, in which teams may not change a car\'s setup. It locks the car into its qualifying configuration for the race save for a narrow list of permitted adjustments.',
  },
  {
    slug: 'slipstream',
    term: 'Slipstream',
    category: 'Aerodynamics',
    aliases: ['tow'],
    definition:
      'The pocket of low-pressure air behind a car. A following driver in the "tow" experiences less drag and can carry more speed to set up an overtake.',
  },
  {
    slug: 'turbo',
    term: 'Turbo',
    category: 'Power Unit',
    aliases: ['turbocharger', 'turbocharged'],
    definition:
      'A compressor driven by exhaust gases that forces more air into the engine for greater power. Defined the original turbo era (1977–1988) and returned with the hybrid power units in 2014.',
  },
  {
    slug: 'undercut',
    term: 'Undercut',
    category: 'Strategy',
    definition:
      'A strategy where a driver pits earlier than a rival and uses fresh-tyre pace to leapfrog them once the rival stops. The opposite move — staying out for track position — is the "overcut".',
  },
];

/** Map for O(1) lookup by slug. */
export const glossaryBySlug: Record<string, GlossaryTerm> = Object.fromEntries(
  glossaryTerms.map((t) => [t.slug, t]),
);
