/**
 * One-shot transform: recovered migration-source story files → tracked
 * `data/stories/content.ts` module with image `src` remapped to the real
 * `public/stories/{slug}/{layout}/{NN}.png` asset scheme (Phase 5 layout).
 *
 * The recovered content references old flat `/Foo.jpg` filenames that no longer
 * exist. We keep the recovered captions/layout but repoint each image block to
 * a real asset: per-layout sequential index, clamped to available files on disk.
 *
 * Run once: `npx tsx scripts/build-story-content.ts`
 * Reads from `.tmp-recover/` (git-extracted), writes `data/stories/content.ts`.
 */

import { readFileSync, writeFileSync, existsSync, readdirSync } from 'node:fs';
import { join } from 'node:path';

const RECOVER_DIR = '.tmp-recover';
const PUBLIC_STORIES = 'public/stories';
const OUT = 'data/stories/content.ts';

type Layout = 'full' | 'landscape' | 'portrait';

// Dynamically import the recovered TS modules (they are plain data exports).
async function main(): Promise<void> {
  const metaSrc = readFileSync(join(RECOVER_DIR, 'storyMetadata.ts'), 'utf8');
  const contentSrc = readFileSync(join(RECOVER_DIR, 'storyContent.ts'), 'utf8');

  // Strip the `import ... from '../types';` lines + type annotations so tsx can
  // eval them as plain JS object/array literals.
  const meta = evalExport(metaSrc, 'storyMetadata');
  const contentMap = evalExport(contentSrc, 'storyContentMap');

  const stories = (meta as MetaItem[]).map((m) => {
    const blocks = (contentMap as Record<string, ContentBlock[]>)[m.id] ?? [];
    // Track per-layout running index so each image maps to NN.png in its folder.
    const counters: Record<Layout, number> = { full: 0, landscape: 0, portrait: 0 };
    const remapped = blocks.map((b) => {
      if (b.type !== 'image') return b;
      const layout = (b.layout ?? 'landscape') as Layout;
      const available = countImages(m.id, layout);
      counters[layout] += 1;
      const idx = available > 0 ? ((counters[layout] - 1) % available) + 1 : counters[layout];
      const nn = String(idx).padStart(2, '0');
      const src = `/stories/${m.id}/${layout}/${nn}.png`;
      // drop the obsolete isBackground hint; keep caption + layout
      const { isBackground: _drop, ...rest } = b;
      void _drop;
      return { ...rest, src };
    });

    return {
      slug: m.id,
      title: m.title,
      subtitle: m.subtitle,
      year: m.year,
      category: m.category,
      // landscape/01 is the canonical card hero per user spec
      heroImage: heroFor(m.id),
      blocks: remapped,
    };
  });

  const banner = `/**
 * AUTO-GENERATED by scripts/build-story-content.ts from recovered
 * migration-source content (git ref a07f942). Do not hand-edit; re-run the
 * script. 17 F1 anthology stories, image src remapped to public/stories scheme.
 */
import type { StoryContentRecord } from './types';

export const storyContent: StoryContentRecord[] = ${JSON.stringify(stories, null, 2)};
`;
  writeFileSync(OUT, banner, 'utf8');
  console.log(`Wrote ${stories.length} stories → ${OUT}`);
}

interface MetaItem {
  id: string;
  title: string;
  subtitle: string;
  year: string;
  category: string;
  heroImage: string;
}
interface ContentBlock {
  type: 'paragraph' | 'quote' | 'heading' | 'image';
  text?: string;
  author?: string;
  src?: string;
  caption?: string;
  layout?: string;
  isBackground?: boolean;
}

function heroFor(slug: string): string {
  const real = countImages(slug, 'landscape') > 0;
  return real ? `/stories/${slug}/landscape/01.png` : '/placeholder.svg';
}

function countImages(slug: string, layout: Layout): number {
  const dir = join(PUBLIC_STORIES, slug, layout);
  if (!existsSync(dir)) return 0;
  return readdirSync(dir).filter((f) => f.endsWith('.png')).length;
}

/** Evaluate a `export const NAME = <literal>;` module body into the literal. */
function evalExport(source: string, name: string): unknown {
  // Remove import lines and TS type annotations on the export declaration.
  const noImports = source.replace(/^\s*import[^\n]*\n/gm, '');
  const assignIdx = noImports.indexOf(`export const ${name}`);
  if (assignIdx === -1) throw new Error(`export const ${name} not found`);
  const eq = noImports.indexOf('=', assignIdx);
  const body = noImports.slice(eq + 1).trimEnd().replace(/;\s*$/, '');
  return Function(`"use strict"; return (${body});`)();
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
