/**
 * Editorial profiles for the current teams, in the Apex house voice
 * (docs/F1_Anlati_Stil_Kilavuzu.md & docs/F1_Anlati_Stil_Kilavuzu_v2.md §7.C).
 * Facts are checked against the F1 history index or widely documented;
 * changing numbers live in the data, not here. The name-by-name story of
 * each team (Stewart to Red Bull, Toleman to Alpine) is generated by the DNA
 * section, so these profiles do not repeat it.
 *
 * English is the base text; `tr` holds the Turkish version.
 */

export interface TeamLoreText {
  /** One short paragraph. */
  bio: string;
  /** Up to 4 milestones ("year: event"). */
  milestones: string[];
  /** One checkable detail; empty when there is nothing safe to add. */
  lore: string;
}

export interface TeamLore extends TeamLoreText {
  /** Ergast/Jolpica constructorId — matches URL slug. */
  constructorId: string;
  /** Current entry name. */
  name: string;
  /** Country of team base. */
  country: string;
  /** First season in Formula 1 under this name. */
  founded: number;
  /** HQ location for map display (decimal degrees). */
  hq: { lat: number; lng: number; label: string };
  /** Turkish version of the text fields. */
  tr: TeamLoreText;
}

const TEAMS: TeamLore[] = [
  {
    constructorId: 'mercedes',
    name: 'Mercedes-AMG Petronas F1 Team',
    country: 'United Kingdom',
    founded: 2010,
    hq: { lat: 52.0406, lng: -1.0157, label: 'Brackley, UK' },
    bio: 'Mercedes came back to Formula 1 in 2010 by buying the champion team it had just seen win, Brawn GP. Four years later the hybrid regulations arrived and the team had understood them first. The result was eight constructors\' titles in a row, from 2014 to 2021, the longest run in the sport. Dominance of that kind is built in factories, long before it shows on a Sunday.',
    milestones: [
      '1954: first season as a works team, with the W196',
      '2010: returns as a works team after buying Brawn GP',
      '2014: first hybrid-era title, and the start of eight in a row',
      '2025: Kimi Antonelli, 18, takes Hamilton\'s seat',
    ],
    lore: 'The team\'s 2014 title was the first of eight consecutive constructors\' championships, ending in 2021.',
    tr: {
      bio: 'Mercedes 2010\'da, az önce kazanan şampiyon takımı Brawn GP\'yi satın alarak Formula 1\'e geri döndü. Dört yıl sonra hibrit yönetmelikler geldi ve takım bunları ilk anlayan olmuştu. Sonuç, 2014\'ten 2021\'e art arda sekiz Markalar Şampiyonluğu, sporun en uzun serisi. Bu tür bir üstünlük pazar günü görünmeden çok önce fabrikalarda kurulur.',
      milestones: [
        '1954: W196 ile fabrika takımı olarak ilk sezon',
        '2010: Brawn GP\'yi satın alarak fabrika takımı olarak dönüş',
        '2014: hibrit çağının ilk şampiyonluğu ve art arda sekizin başlangıcı',
        '2025: 18 yaşındaki Kimi Antonelli, Hamilton\'ın koltuğuna oturur',
      ],
      lore: 'Takımın 2014 şampiyonluğu, 2021\'de biten art arda sekiz Markalar Şampiyonluğu\'nun ilkiydi.',
    },
  },
  {
    constructorId: 'red_bull',
    name: 'Oracle Red Bull Racing',
    country: 'Austria',
    founded: 2005,
    hq: { lat: 52.1087, lng: -1.0254, label: 'Milton Keynes, UK' },
    bio: 'Red Bull is a drinks company that decided to become a racing team, and then a racing team that decided to be better at it than anyone. It started in 2005 from the remains of Jaguar, won its first Grand Prix in 2009, and in 2010 began a run of four straight constructors\' titles with Sebastian Vettel. Two more followed in 2022 and 2023, with Max Verstappen. The cars behind every one of those titles came from Adrian Newey\'s design office.',
    milestones: [
      '2005: first season, in the Jaguar factory in Milton Keynes',
      '2009: first win, China',
      '2010 to 2013: four consecutive constructors\' titles',
      '2022 and 2023: back-to-back constructors\' titles with Verstappen',
    ],
    lore: 'Verstappen won the drivers\' title four years in a row, from 2021 to 2024.',
    tr: {
      bio: 'Red Bull, yarış takımı olmaya karar veren bir içecek şirketi; sonra da bu işte herkesten iyi olmaya karar veren bir yarış takımı. 2005\'te Jaguar\'ın kalıntılarından başladı, ilk Grand Prix\'sini 2009\'da kazandı ve 2010\'da Sebastian Vettel ile art arda dört Markalar Şampiyonluğu serisini açtı. 2022 ve 2023\'te Max Verstappen ile iki tane daha geldi. Bu şampiyonlukların hepsinin arkasındaki araçlar Adrian Newey\'in tasarım ofisinden çıktı.',
      milestones: [
        '2005: Milton Keynes\'teki eski Jaguar fabrikasında ilk sezon',
        '2009: ilk galibiyet, Çin',
        '2010–2013: art arda dört Markalar Şampiyonluğu',
        '2022 ve 2023: Verstappen ile art arda Markalar Şampiyonluğu',
      ],
      lore: 'Verstappen, 2021\'den 2024\'e art arda dört yıl pilotlar şampiyonluğunu kazandı.',
    },
  },
  {
    constructorId: 'ferrari',
    name: 'Scuderia Ferrari',
    country: 'Italy',
    founded: 1950,
    hq: { lat: 44.5308, lng: 10.8611, label: 'Maranello, Italy' },
    bio: 'Ferrari is not only a team, it is the only constant of the championship. It has raced in every season since 1950 and holds the record for Grands Prix won. It also holds the record for waiting: sixteen constructors\' titles, none since 2008. Few teams in sport are asked, every spring, to be what they were. Even fewer keep trying.',
    milestones: [
      '1950: enters the first world championship',
      '1951: first win, Silverstone',
      '1999 to 2004: six consecutive constructors\' titles',
      '2025: Lewis Hamilton joins',
    ],
    lore: 'Ferrari is the only team to have entered every Formula 1 World Championship season since 1950.',
    tr: {
      bio: 'Ferrari yalnızca bir takım değil, şampiyonanın tek değişmeyen öğesidir. 1950\'den beri her sezonda yarıştı ve en çok Grand Prix kazanma rekoru onda. Beklemenin rekoru da onda: on altı Markalar Şampiyonluğu, 2008\'den beri hiçbiri yok. Sporda az sayıda takımdan her bahar eskiden olduğu şey olması beklenir. Çok daha azı denemeyi bırakmaz.',
      milestones: [
        '1950: ilk dünya şampiyonasına katılır',
        '1951: ilk galibiyet, Silverstone',
        '1999–2004: art arda altı Markalar Şampiyonluğu',
        '2025: Lewis Hamilton katılır',
      ],
      lore: 'Ferrari, 1950\'den beri Formula 1 Dünya Şampiyonası\'nın her sezonuna katılmış tek takım.',
    },
  },
  {
    constructorId: 'mclaren',
    name: 'McLaren Mastercard F1 Team',
    country: 'United Kingdom',
    founded: 1966,
    hq: { lat: 51.3427, lng: -0.5461, label: 'Woking, UK' },
    bio: 'McLaren has changed shape more than once and kept the same stubbornness. Founded by Bruce McLaren, in Formula 1 since 1966, it won its first constructors\' title in 1974 and built the most overwhelming car of its age in 1988, winning fifteen of sixteen races. After long years of decline it climbed back, and in 2024 and 2025 it won the constructors\' title twice running. A team that knows how to come back.',
    milestones: [
      '1966: first season in Formula 1',
      '1974: first constructors\' title',
      '1988: wins fifteen of sixteen races with the MP4/4',
      '2024 and 2025: back-to-back constructors\' titles',
    ],
    lore: 'McLaren has raced in every season since its 1966 debut.',
    tr: {
      bio: 'McLaren birkaç kez şekil değiştirdi ve aynı inadı korudu. Bruce McLaren tarafından kurulan, 1966\'dan beri Formula 1\'de olan takım ilk Markalar Şampiyonluğu\'nu 1974\'te kazandı ve 1988\'de çağının en ezici aracını yaparak on altı yarışın on beşini aldı. Uzun düşüş yıllarının ardından geri tırmandı; 2024 ve 2025\'te Markalar Şampiyonluğu\'nu art arda iki kez kazandı. Geri dönmeyi bilen bir takım.',
      milestones: [
        '1966: Formula 1\'de ilk sezon',
        '1974: ilk Markalar Şampiyonluğu',
        '1988: MP4/4 ile on altı yarışın on beşini kazanır',
        '2024 ve 2025: art arda Markalar Şampiyonluğu',
      ],
      lore: 'McLaren, 1966\'daki ilk yarışından beri her sezonda yarıştı.',
    },
  },
  {
    constructorId: 'aston_martin',
    name: 'Aston Martin Aramco F1 Team',
    country: 'United Kingdom',
    founded: 2021,
    hq: { lat: 52.0748, lng: -1.0302, label: 'Silverstone, UK' },
    bio: 'Aston Martin is the youngest name on a very old team. In 2018 a consortium led by Lawrence Stroll saved the bankrupt Force India, raced it as Racing Point, and in 2021 renamed it for a brand that had last been in Formula 1 in 1960. Fernando Alonso\'s arrival in 2023 turned a promise into podiums almost overnight. What the team builds next in Silverstone is the real test.',
    milestones: [
      '2018: Stroll\'s consortium rescues Force India, which becomes Racing Point',
      '2021: renamed Aston Martin, the first Formula 1 entry under that name since 1960',
      '2023: Alonso joins and takes eight podiums in his first season',
    ],
    lore: 'The Aston Martin name had last appeared in Formula 1 in 1960.',
    tr: {
      bio: 'Aston Martin, çok eski bir takımın en genç adı. 2018\'de Lawrence Stroll\'un başını çektiği bir grup iflas eden Force India\'yı kurtardı, Racing Point adıyla yarıştırdı ve 2021\'de Formula 1\'de en son 1960\'ta görülmüş bir markanın adını verdi. Fernando Alonso\'nun 2023\'teki gelişi, bir vaadi neredeyse bir gecede podyumlara çevirdi. Silverstone\'da sırada ne inşa edecekleri asıl sınav.',
      milestones: [
        '2018: Stroll\'un grubu Force India\'yı kurtarır, takım Racing Point olur',
        '2021: Aston Martin adını alır, 1960\'tan beri bu adla ilk Formula 1 katılımı',
        '2023: Alonso katılır ve ilk sezonunda sekiz podyum alır',
      ],
      lore: 'Aston Martin adı Formula 1\'de en son 1960\'ta görülmüştü.',
    },
  },
  {
    constructorId: 'alpine',
    name: 'BWT Alpine Formula One Team',
    country: 'France',
    founded: 2021,
    hq: { lat: 51.9086, lng: -1.4339, label: 'Enstone, UK' },
    bio: 'Alpine is the latest name on a team that has changed it more than any other: Toleman, Benetton, Renault, Lotus, Renault again. The chassis are still built in Enstone, in the same corner of Oxfordshire. In 2021 the Renault group put its sports-car brand on the car and won in Hungary within the year. The story of this team is a very long list of new beginnings.',
    milestones: [
      '2005 and 2006: constructors\' and drivers\' titles with Renault and Fernando Alonso',
      '2021: renamed Alpine',
      '2021: Esteban Ocon wins in Hungary',
      '2025: Franco Colapinto joins mid-season',
    ],
    lore: 'The 2005 and 2006 championships were won by the same factory in Enstone that builds Alpine\'s chassis today.',
    tr: {
      bio: 'Alpine, adını başka hiçbir takımdan daha fazla değiştirmiş bir takımın en yeni adı: Toleman, Benetton, Renault, Lotus, yine Renault. Şasiler hâlâ Enstone\'da, Oxfordshire\'ın aynı köşesinde üretiliyor. 2021\'de Renault grubu spor otomobil markasını araca yazdı ve aynı yıl Macaristan\'da kazandı. Bu takımın hikâyesi, çok uzun bir yeni başlangıçlar listesi.',
      milestones: [
        '2005 ve 2006: Renault ve Fernando Alonso ile hem takımlar hem sürücüler şampiyonluğu',
        '2021: Alpine adını alır',
        '2021: Esteban Ocon Macaristan\'da kazanır',
        '2025: Franco Colapinto sezon ortasında katılır',
      ],
      lore: '2005 ve 2006 şampiyonluklarını, bugün Alpine\'in şasilerini üreten Enstone\'daki aynı fabrika kazandı.',
    },
  },
  {
    constructorId: 'williams',
    name: 'Williams Racing',
    country: 'United Kingdom',
    founded: 1978,
    hq: { lat: 51.3453, lng: -1.1385, label: 'Grove, UK' },
    bio: 'Frank Williams built his team from nothing, saw it sold when the money ran out, and built it again. The second team, the one that bears his name, raced from 1978, won nine constructors\' titles between 1980 and 1997, and remained family-run until 2020, when Dorilton Capital bought it. Its history has the shape of a long climb, a long peak and a slow, honest rebuilding. Carlos Sainz joined for 2025, the signal that it means it.',
    milestones: [
      '1978: first season as Williams Grand Prix Engineering',
      '1980: first constructors\' title',
      '1997: ninth and last constructors\' title',
      '2020: sold to Dorilton Capital',
    ],
    lore: 'The team has won nine constructors\' championships, the last in 1997.',
    tr: {
      bio: 'Frank Williams takımını sıfırdan kurdu, para bitince satıldığını gördü ve yeniden kurdu. Adını taşıyan ikinci takım 1978\'den itibaren yarıştı, 1980 ile 1997 arasında dokuz Markalar Şampiyonluğu kazandı ve 2020\'de Dorilton Capital satın alana dek aile işletmesi olarak kaldı. Tarihi uzun bir tırmanışın, uzun bir zirvenin ve yavaş, dürüst bir yeniden inşanın şeklini taşıyor. Carlos Sainz\'ın 2025\'te katılması, bu işin ciddiye alındığının işareti.',
      milestones: [
        '1978: Williams Grand Prix Engineering olarak ilk sezon',
        '1980: ilk Markalar Şampiyonluğu',
        '1997: dokuzuncu ve son Markalar Şampiyonluğu',
        '2020: Dorilton Capital\'a satış',
      ],
      lore: 'Takım dokuz Markalar Şampiyonluğu kazandı; sonuncusu 1997\'de.',
    },
  },
  {
    constructorId: 'haas',
    name: 'TGR Haas F1 Team',
    country: 'United States',
    founded: 2016,
    hq: { lat: 35.7279, lng: -80.8598, label: 'Kannapolis, NC, USA' },
    bio: 'Haas is Formula 1\'s experiment in doing more with less. Founded by American businessman Gene Haas, it entered in 2016 and scored points in its first race, a rare thing for a new team. It buys what it can, mainly from Ferrari, and builds the rest. Its best constructors\' finish is fifth, in 2018. The question it keeps asking the grid is how much of the sport can be outsourced.',
    milestones: [
      '2016: points in its first race, Australia',
      '2018: fifth in the constructors\' championship, its best result',
      '2025: Esteban Ocon and Oliver Bearman as the line-up',
    ],
    lore: '',
    tr: {
      bio: 'Haas, Formula 1\'in "daha azla daha fazlasını yapma" deneyi. Amerikalı iş insanı Gene Haas tarafından kurulan takım 2016\'da katıldı ve yeni bir takım için ender görülen bir şekilde ilk yarışında puan aldı. Alabildiğini, başta Ferrari\'den, satın alıyor; gerisini üretiyor. En iyi Markalar sıralaması 2018\'deki beşincilik. Gride sürekli sorduğu soru, sporun ne kadarının dışarıdan sağlanabileceği.',
      milestones: [
        '2016: ilk yarışında puan, Avustralya',
        '2018: Markalar Şampiyonası\'nda beşincilik, en iyi sonuç',
        '2025: Esteban Ocon ve Oliver Bearman kadroda',
      ],
      lore: '',
    },
  },
  {
    constructorId: 'rb',
    name: 'Visa Cash App Racing Bulls',
    country: 'Italy',
    founded: 2006,
    hq: { lat: 44.6952, lng: 11.1839, label: 'Faenza, Italy' },
    bio: 'The team in Faenza has two jobs: race, and train the next Red Bull driver. It was Minardi, small and loved, until Red Bull bought it and called it Toro Rosso. It has also won twice: Sebastian Vettel at Monza in 2008, and Pierre Gasly there in 2020. Since then it has gone through AlphaTauri, RB and Racing Bulls. The names keep changing; the Monza tradition does not.',
    milestones: [
      '2006: first season as Toro Rosso after Red Bull bought Minardi',
      '2008: Sebastian Vettel wins at Monza',
      '2020: Pierre Gasly wins at Monza, as AlphaTauri',
      '2025: becomes Racing Bulls',
    ],
    lore: 'Both of the team\'s Grand Prix wins came at Monza.',
    tr: {
      bio: 'Faenza\'daki takımın iki görevi var: yarışmak ve sıradaki Red Bull sürücüsünü yetiştirmek. Red Bull satın alıp Toro Rosso adını verene kadar küçük ve sevilen Minardi\'ydi. İki kez de kazandı: 2008\'de Monza\'da Sebastian Vettel, 2020\'de yine orada Pierre Gasly. Sonra AlphaTauri, RB ve Racing Bulls adlarından geçti. İsimler değişiyor; Monza geleneği değişmiyor.',
      milestones: [
        '2006: Red Bull Minardi\'yi satın alır, Toro Rosso olarak ilk sezon',
        '2008: Sebastian Vettel Monza\'da kazanır',
        '2020: Pierre Gasly Monza\'da AlphaTauri olarak kazanır',
        '2025: Racing Bulls adını alır',
      ],
      lore: 'Takımın iki Grand Prix galibiyeti de Monza\'da geldi.',
    },
  },
  {
    constructorId: 'kick_sauber',
    name: 'Stake F1 Team Kick Sauber',
    country: 'Switzerland',
    founded: 1993,
    hq: { lat: 47.4980, lng: 8.2185, label: 'Hinwil, Switzerland' },
    bio: 'Sauber has been racing since 1993 from the same Swiss factory in Hinwil, founded by Peter Sauber. It raced as BMW Sauber for a few years, won once, with Robert Kubica in Canada in 2008, and ran under sponsor names ever since. In 2025 its drivers Nico Hülkenberg and Gabriel Bortoleto gave it a long-awaited podium at Silverstone, a farewell worth keeping. The next chapter belongs to Audi.',
    milestones: [
      '1993: first season; Peter Sauber\'s team takes points in its first race',
      '2008: Robert Kubica wins the Canadian Grand Prix as BMW Sauber',
      '2025: Nico Hülkenberg\'s podium at Silverstone',
    ],
    lore: '',
    tr: {
      bio: 'Sauber 1993\'ten beri, Peter Sauber\'in kurduğu Hinwil\'deki aynı İsviçre fabrikasından yarışıyor. Birkaç yıl BMW Sauber olarak yarıştı, 2008\'de Kanada\'da Robert Kubica ile bir kez kazandı ve o günden beri sponsor adlarıyla yarıştı. 2025\'te Nico Hülkenberg\'in Silverstone\'daki podyumu, uzun süredir beklenen bir veda armağanı oldu. Sonraki bölüm Audi\'nin.',
      milestones: [
        '1993: ilk sezon; Peter Sauber\'in takımı ilk yarışında puan alır',
        '2008: Robert Kubica BMW Sauber olarak Kanada Grand Prix\'sini kazanır',
        '2025: Nico Hülkenberg\'in Silverstone\'daki podyumu',
      ],
      lore: '',
    },
  },
  {
    constructorId: 'audi',
    name: 'Audi Revolut F1 Team',
    country: 'Germany',
    founded: 2026,
    hq: { lat: 47.4980, lng: 8.2185, label: 'Hinwil, Switzerland' },
    bio: 'Audi did not build a Formula 1 team from scratch. It took the best thing available, the Sauber factory in Hinwil, and put its own power unit and its own name on top. The 2026 regulations were the reason to come: new engines, new chances for a new works team. A manufacturer that waits for the rules to change, then moves.',
    milestones: [
      '2022: Audi announces its Formula 1 entry for 2026',
      '2026: first season as a works team, in the Hinwil factory',
    ],
    lore: '',
    tr: {
      bio: 'Audi sıfırdan bir Formula 1 takımı kurmadı. Elindeki en iyi şeyi, Hinwil\'deki Sauber fabrikasını aldı ve üzerine kendi güç ünitesini ve kendi adını koydu. Gelme nedeni 2026 yönetmelikleriydi: yeni motorlar, yeni bir fabrika takımı için yeni şanslar. Kuralların değişmesini bekleyip sonra harekete geçen bir üretici.',
      milestones: [
        '2022: Audi 2026 için Formula 1 katılımını açıklar',
        '2026: Hinwil fabrikasında fabrika takımı olarak ilk sezon',
      ],
      lore: '',
    },
  },
  {
    constructorId: 'cadillac',
    name: 'Cadillac Formula 1 Team',
    country: 'United States',
    founded: 2026,
    hq: { lat: 35.2271, lng: -80.8431, label: 'Charlotte, NC, USA' },
    bio: 'Cadillac is the eleventh team of the 2026 grid, and the first to be admitted after years in which the answer to new entries was no. It began as Andretti\'s bid, in 2022, and became a General Motors project. The first driver pairing, Valtteri Bottas and Sergio Pérez, is the clearest sign of the plan: experience first, then the future.',
    milestones: [
      '2022: Andretti Global announces its Formula 1 bid',
      '2025: approved to join as the eleventh team',
      '2026: first season, with Valtteri Bottas and Sergio Pérez',
    ],
    lore: '',
    tr: {
      bio: 'Cadillac, 2026 gridinin on birinci takımı ve yeni katılımlara yıllarca "hayır" denen bir dönemden sonra kabul edilen ilk takım. 2022\'de Andretti\'nin başvurusu olarak başladı, General Motors projesine dönüştü. İlk sürücü ikilisi Valtteri Bottas ve Sergio Pérez, planın en açık işareti: önce deneyim, sonra gelecek.',
      milestones: [
        '2022: Andretti Global Formula 1 başvurusunu açıklar',
        '2025: on birinci takım olarak katılımı onaylanır',
        '2026: Valtteri Bottas ve Sergio Pérez ile ilk sezon',
      ],
      lore: '',
    },
  },
];

const MAP = new Map(TEAMS.map((t) => [t.constructorId, t]));

/** Editorial profile of a team; with `locale` "tr" the text fields are in Turkish. */
export function getTeamLore(constructorId: string, locale?: string): TeamLore | null {
  const lore = MAP.get(constructorId.toLowerCase());
  if (!lore) return null;
  if (locale !== 'tr') return lore;
  return { ...lore, ...lore.tr };
}
