import { GlossaryTerm } from './types';

const GLOSSARY_TERMS: GlossaryTerm[] = [
  // Terms from data/glossary/terms.ts
  {
    term: 'Active Suspension',
    category: 'Chassis',
    definition:
      'A computer-controlled suspension that adjusts ride height and stiffness in real time to keep the car at its aerodynamic optimum. Dominant in the early 1990s (notably the Williams FW14B/FW15C) before being banned for 1994.',
  },
  {
    term: 'Diffuser',
    category: 'Aerodynamics',
    definition:
      'The upswept rear section of the floor that accelerates airflow under the car and expands it at the exit, lowering pressure to generate downforce. The 2009 "double diffuser" exploited a regulatory loophole to enormous effect.',
  },
  {
    term: 'Downforce',
    category: 'Aerodynamics',
    definition:
      'Aerodynamic load pressing the car onto the track, increasing mechanical grip through the tyres. More downforce means higher cornering speed at the cost of straight-line drag.',
  },
  {
    term: 'DRS',
    category: 'Aerodynamics',
    definition:
      'Drag Reduction System: a driver-operated flap in the rear wing that opens within designated zones to cut drag and aid overtaking, permitted only when within one second of the car ahead.',
  },
  {
    term: 'ERS',
    category: 'Power Unit',
    definition:
      'Energy Recovery System: harvests energy under braking (MGU-K) and from exhaust heat (MGU-H), stores it in a battery, and redeploys it for extra power. Its forerunner, KERS, appeared in 2009.',
  },
  {
    term: 'Graining',
    category: 'Tyres',
    definition:
      'A surface tearing of the tyre where rubber rolls into small strips, reducing the contact patch and grip. Caused by sliding on a cold or overworked tyre.',
  },
  {
    term: 'Ground Effect',
    category: 'Aerodynamics',
    definition:
      'Downforce generated by shaping the floor and underbody to create a low-pressure region beneath the car. Central to late-1970s/early-1980s design and reintroduced under the 2022 regulations.',
  },
  {
    term: 'Parc Fermé',
    category: 'Regulations',
    definition:
      "The state, beginning at qualifying, in which teams may not change a car's setup. It locks the car into its qualifying configuration for the race save for a narrow list of permitted adjustments.",
  },
  {
    term: 'Slipstream',
    category: 'Aerodynamics',
    definition:
      'The pocket of low-pressure air behind a car. A following driver in the "tow" experiences less drag and can carry more speed to set up an overtake.',
  },
  {
    term: 'Turbo',
    category: 'Power Unit',
    definition:
      'A compressor driven by exhaust gases that forces more air into the engine for greater power. Defined the original turbo era (1977–1988) and returned with the hybrid power units in 2014.',
  },
  {
    term: 'Undercut',
    category: 'Strategy',
    definition:
      'A strategy where a driver pits earlier than a rival and uses fresh-tyre pace to leapfrog them once the rival stops. The opposite move — staying out for track position — is the "overcut".',
  },
  // Tyre compounds from data/glossary/tyres.ts
  {
    term: 'C1 — Hardest',
    category: 'Tyres',
    definition:
      'The hardest slick in the range. Slowest to warm up but the most durable, it is chosen for the highest-energy circuits (heavy braking, abrasive surfaces) where softer rubber would overheat and grain. Long stints, low degradation, least outright grip.',
  },
  {
    term: 'C2 — Hard',
    category: 'Tyres',
    definition:
      'A workhorse hard compound. A strong one-stop tyre that trades a little peak grip for consistency across a long run — frequently the race tyre at demanding venues.',
  },
  {
    term: 'C3 — Medium',
    category: 'Tyres',
    definition:
      'The balanced middle of the range, and the most versatile compound. It can act as a hard or a soft depending on which three compounds Pirelli nominates for a given weekend.',
  },
  {
    term: 'C4 — Soft',
    category: 'Tyres',
    definition:
      'A high-grip soft for twisty, lower-energy circuits. Quick to switch on and strong over a single lap, but it gives up life in exchange — usually a qualifying or short-stint tyre.',
  },
  {
    term: 'C5 — Softest',
    category: 'Tyres',
    definition:
      'The softest, grippiest slick. Enormous one-lap pace for street circuits and qualifying, but it degrades fastest — drivers must manage it carefully if they race on it.',
  },
  {
    term: 'Intermediate',
    category: 'Tyres',
    definition:
      'The crossover tyre for a damp or drying track. Its tread clears standing water at lower volumes than the full wet, and it is the fastest tyre in the narrow window between slick conditions and heavy rain.',
  },
  {
    term: 'Full Wet',
    category: 'Tyres',
    definition:
      'The deep-tread rain tyre, able to disperse the most water and resist aquaplaning in the heaviest conditions. It runs cooler and offers the most grip when the track is truly flooded, but is slow once a dry line appears.',
  },
];

export function getGlossaryTerms(): GlossaryTerm[] {
  return GLOSSARY_TERMS.slice().sort((a, b) => a.term.localeCompare(b.term));
}
